-- MySQL Script generated by MySQL Workbench
-- 09/03/16 16:45:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bbs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bbs` DEFAULT CHARACTER SET utf8 ;
USE `bbs` ;

-- -----------------------------------------------------
-- Table `bbs`.`awards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bbs`.`awards` ;

CREATE TABLE IF NOT EXISTS `bbs`.`awards` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `awards_type` VARCHAR(45) NULL DEFAULT NULL COMMENT '优惠券类型',
  `awards_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '奖项名称',
  `awards_num` INT(11) NULL DEFAULT NULL COMMENT '数量',
  `probability` DECIMAL(6,4) NULL DEFAULT NULL COMMENT '中奖概率',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '奖项表';


-- -----------------------------------------------------
-- Table `bbs`.`awards_records`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bbs`.`awards_records` ;

CREATE TABLE IF NOT EXISTS `bbs`.`awards_records` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `post_id` INT(11) NOT NULL,
  `award_id` INT(11) NOT NULL,
  `awards_content` VARCHAR(45) NULL DEFAULT NULL COMMENT '中奖内容',
  `create_time` DATETIME NULL DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '中奖记录表';


-- -----------------------------------------------------
-- Table `bbs`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bbs`.`post` ;

CREATE TABLE IF NOT EXISTS `bbs`.`post` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL COMMENT '发帖人',
  `title` VARCHAR(100) NOT NULL COMMENT '标题',
  `content` TEXT NULL DEFAULT NULL COMMENT '内容',
  `content_copy` TEXT NULL DEFAULT NULL COMMENT '内容副本',
  `section_id` INT(11) NULL DEFAULT NULL COMMENT '所属板块',
  `publish_time` DATETIME NULL DEFAULT NULL COMMENT '发帖时间',
  `browse_num` INT(11) NULL DEFAULT 0 COMMENT '浏览量',
  `comment_num` INT(11) NULL DEFAULT 0 COMMENT '评论数量',
  `thumb_num` INT(11) NULL DEFAULT 0 COMMENT '点赞数',
  `is_approve` INT(1) NULL DEFAULT 1 COMMENT '是否已审批(0否、1是)',
  `status` INT(1) NULL DEFAULT 0 COMMENT '帖子状态(0普通、1精华)',
  `top` INT(1) NULL DEFAULT 0 COMMENT '帖子置顶 1置顶 0不置顶',
  `type` INT(1) NULL DEFAULT 0 COMMENT '帖子类型(0讨论帖 1投票贴)',
  `expire_time` DATETIME NULL DEFAULT NULL COMMENT '投票贴结束时间',
  `is_delete` INT(1) NULL DEFAULT 0 COMMENT '是否删除(1是0否)',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '帖子';

-- ----------------------------
-- Table structure for user_thumb_post
-- ----------------------------
DROP TABLE IF EXISTS `user_thumb_post`;
CREATE TABLE `user_thumb_post` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `postId` int(11) DEFAULT NULL COMMENT '该用户点赞的帖子id',
  `userId` int(11) DEFAULT NULL COMMENT '用户id',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户点赞记录表';


-- -----------------------------------------------------
-- Table `bbs`.`post_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bbs`.`post_comment` ;

CREATE TABLE IF NOT EXISTS `bbs`.`post_comment` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `post_id` INT(11) NOT NULL,
  `content` VARCHAR(500) NOT NULL COMMENT '评论内容',
  `create_time` DATETIME NULL DEFAULT NULL COMMENT '评论时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '帖子评论表';


-- -----------------------------------------------------
-- Table `bbs`.`post_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bbs`.`post_image` ;

CREATE TABLE IF NOT EXISTS `bbs`.`post_image` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `post_id` INT(11) NOT NULL,
  `img_url` VARCHAR(255) NULL DEFAULT NULL COMMENT '图片路径',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '帖子图片';


-- -----------------------------------------------------
-- Table `bbs`.`section`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bbs`.`section` ;

CREATE TABLE IF NOT EXISTS `bbs`.`section` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT '版块名称',
  `is_delete` INT(1) NOT NULL DEFAULT 0 COMMENT '是否删除(1是0否)',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '版块';


-- -----------------------------------------------------
-- Table `bbs`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bbs`.`user` ;

CREATE TABLE IF NOT EXISTS `bbs`.`user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(45) DEFAULT NULL COMMENT '用户名',
  `openid` varchar(45) NOT NULL COMMENT '用户标识',
  `nick_name` varchar(45) NOT NULL COMMENT '昵称',
  `avatar` varchar(255) DEFAULT NULL COMMENT '图像',
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '用户表';

-- -----------------------------------------------------
-- Table `bbs`.`user_thumb_post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bbs`.`user_thumb_post` ;

CREATE TABLE IF NOT EXISTS `bbs`.`user_thumb_post` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `postId` varchar(45) DEFAULT NULL COMMENT '帖子',
  `userId` varchar(45) NOT NULL COMMENT '用户',
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COMMENT = '用户发帖表';


-- -----------------------------------------------------
-- Table `bbs`.`vote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bbs`.`vote` ;

CREATE TABLE IF NOT EXISTS `bbs`.`vote` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `post_id` INT(11) NOT NULL,
  `instructions` VARCHAR(100) NULL DEFAULT NULL COMMENT '投票说明',
  `status` INT(1) NOT NULL COMMENT '状态(0、正在进行 1、已经结束)',
  `vote_num` INT(11) NULL DEFAULT 0 COMMENT '已有投票人数',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '投票信息';


-- -----------------------------------------------------
-- Table `bbs`.`vote_candidate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bbs`.`vote_candidate` ;

CREATE TABLE IF NOT EXISTS `bbs`.`vote_candidate` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `vote_id` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL COMMENT '候选人姓名',
  `avatar` VARCHAR(255) NULL DEFAULT NULL COMMENT '候选人图像',
  `introduction` VARCHAR(500) NULL DEFAULT NULL COMMENT '候选人介绍',
  `votes` INT NOT NULL DEFAULT 0 COMMENT '获得票数',
  `cheat_vote` INT(11) NULL DEFAULT 0 COMMENT '作弊票数',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '投票候选人';


DROP TABLE IF EXISTS `bbs`.`user_vote` ;

CREATE TABLE `bbs`.`user_vote` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `vote_id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL COMMENT '投给的候选人',
  `vote_time` DATETIME NULL COMMENT '投票时间',
  PRIMARY KEY (`id`))
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COMMENT = '用户投票记录表';


DROP TABLE IF EXISTS `bbs`.`vote_config` ;
  CREATE TABLE `bbs`.`vote_config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post_id` INT(11) NOT NULL,
  `vote_freq` INT(1) NOT NULL COMMENT '投票频率(1仅投一次2每天都投)',
  `vote_times` INT NULL COMMENT '每天能投票次数',
  `max_vote` INT NOT NULL COMMENT '最多能投几个',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '投票配置表';




set character_set_server=utf8mb4;
alter table user convert to character set utf8mb4 collate utf8mb4_bin;

alter table post_comment convert to character set utf8mb4 collate utf8mb4_bin;

TRUNCATE TABLE `user`;
INSERT INTO `user` (`id`,`name`,`openid`,`nick_name`,`avatar`) VALUES (1,'admin','21232f297a57a5a743894a0e4a801fc3','管理员','/microForum/images/header-img.png');

TRUNCATE TABLE `section`;
INSERT INTO `bbs`.`section` (`id`, `name`, `is_delete`) VALUES ('1', '默认', '0');




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
